site_name: roy-n-roy メモ
theme:
  name: null
  custom_dir: 'submodules/mkdocs-material/material'
  logo: 'imgs/logo.svg'
  favicon: 'imgs/favicon.ico'
  language: 'ja'
  feature:
    tabs: true
  include_search_page: false
  search_index_only: true
  static_templates:
    - 404.html
  palette:
    primary: 'deep orange'
  font:
    text: Roboto
    code: Roboto Mono
site_url: 'https://roy-n-roy.github.io/'
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
plugins:
  - search
  - git-revision-date-localized
remote_branch: master
extra:
  search:
    language: 'ja'
  social:
    - type: 'github'
      link: 'https://github.com/roy-n-roy/'
    - type: 'twitter'
      link: 'https://twitter.com/roy_n_roy/'
extra_javascript:
    - 'lightbox2/js/lightbox-plus-jquery.min.js'
extra_css:
    - 'lightbox2/css/lightbox.min.css'
    - 'styles/git_revision_date.css'
google_analytics:
  - 'UA-149709379-1'
  - 'auto'