site_name: roy-n-roy メモ
theme:
  name: material
  logo: imgs/logo.svg
  favicon: imgs/favicon.ico
  language: ja
  features:
    - tabs
  palette:
    primary: deep orange
site_url: https://roy-n-roy.github.io/
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true
remote_branch: master
extra:
  search:
    language: ja
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/roy-n-roy/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/roy_n_roy/
extra_javascript:
    - lightbox2/js/lightbox-plus-jquery.min.js
extra_css:
    - lightbox2/css/lightbox.min.css
    - styles/git_revision_date.css
google_analytics:
  - UA-149709379-1
  - auto