site_name: roy-n-roy メモ
site_author: Roy.
site_description: Windows, Network, Docker, Raspberry Pi などについて、調べたこと/やってみたことをメモ書き
site_url: https://roy-n-roy.github.io/
repo_name: roy-n-roy.github.io
repo_url: https://github.com/roy-n-roy/roy-n-roy.github.io
remote_name: origin
remote_branch: master
#edit_uri: edit/release/docs/
edit_uri: ''
copyright: © 2019- Roy.
theme:
  name: material
  logo: imgs/logo.svg
  favicon: imgs/favicon.ico
  language: ja
  features:
    - tabs
  palette:
    primary: deep orange
    accent: deep orange
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.tilde
plugins:
  - search:
      lang:
        - ja
  - git-revision-date-localized
  - minify:
      minify_html: true
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/roy-n-roy/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/roy_n_roy/
extra_javascript:
    - lightbox2/js/lightbox-plus-jquery.min.js
extra_css:
    - lightbox2/css/lightbox.min.css
    - styles/git_revision_date.css
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_TRACKING_ID"]
  - auto