[tool.poetry]
name = "roy-n-roy.github.io"
version = "1.0.0"
description = "roy-n-roy's memo docs"
authors = ["Roy <royroy.euph@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
mkdocs-material = {git = "https://github.com/roy-n-roy/mkdocs-material.git", rev = "edit"}
mkdocs-git-revision-date-localized-plugin = "^0.5.2"
mkdocs-minify-plugin = "^0.3.0"

[tool.poetry.dev-dependencies]
aiohttp = {extras = ["speedups"], version = "^3.6.2"}
autopep8 = "^1.5.3"
beautifulsoup4 = "^4.9.1"
flake8 = "^3.8.3"
lxml = "^4.5.1"
pytest = "^5.4"
requests = "^2.24.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
